Feat/add masques
s2unga9/mimik pull request #6
Opened 2017-12-01 12:22 UTC by LEEhajeong

https://app.asana.com/0/487815437712560/487815437712576

2017-12-01 14:42 UTC, yoonjechoi requested changes

2017-12-01 14:42 UTC, yoonjechoi commented on src/App.js
> +        {/* <Header />
<Header />
{
  <Product .../> 
}

다 필요한 것같은데요?
header
productList
HowToUse
넣을것같은데데
comment처리한거 원래대로 header, productlist,howtouse 다표시되게 해서 commit해주세요.
수정해서  feat/add-masques  브랜치에 커밋하고 push하면 저절로 이 pull request아래에 추가됩니다.

2017-12-01 14:42 UTC, yoonjechoi commented on src/How_to_use.jsx
> +class HowToUse extends Component {
👍

2017-12-01 14:42 UTC, yoonjechoi commented on src/How_to_use.css
> +@import "reset.css";
👍

2017-12-03 08:38 UTC, s2unga9 commented on src/App.js
>          {products.map((products, index) =>
👍

2017-12-03 08:39 UTC, s2unga9 approved these changes

2017-12-04 05:55 UTC, yoonjechoi approved these changes

2017-12-04 06:00 UTC, merged